### PR TITLE
Upgrade (with full manual sync of files) to Phoenix 0.13.0

### PR DESCRIPTION
**Pull request by grempe**
One thing that will need to change, once you have merged my other pull request on phoenix_token_auth and pushed a new version, is to switch back to using that canonical version from hex.pm.  Right now it is configured in mix.exs to use my personal fork at grempe/phoenix_token_auth.

I have not done any work looking into brunch vs. webpack. I will investigate that so I can learn more about them. Right now they are both installed (and things seem to be working ok).

I'll probably have more in a couple of days.

Cheers,

Glenn

### CODE REVIEW

**Comment by manukall** [comment]
hey @grempe,
looks great. i don't have a lot of time at the moment, so i'm really happy about you keeping the project up to date.

i'm not sure about the brunch stuff yet. it might be confusing for others if we have both brunch and webpack. on the other hand, i find webpack to be much simpler, though i haven't really used brunch except for trying it out.
on the other hand i totally see the benefit of sticking to brunch, as it is phoenix's default.

**Comment by manukall** [comment]
@grempe do you still want to work on this? i pushed an update for phoenix_token_auth 0.0.12, so you would probably need to fix some merge conflicts. if you could then just remove the brunch stuff (i think it's only the config), i would be more than happy to merge this.

**Comment by grempe** [comment]
I'll try to get it cleaned up in the next couple of days so you can pull in the updates.

Thx

**Comment by ACPK** [comment]
@grempe Any progress cleaning it up as I'd love to see it?

**Comment by grempe** [comment]
Sorry no. I've shifted away from using Phoenix for now for a project I am
working on and I can't find the time at the moment.

**Pull request closed without merging**
